# Generated by Django 3.1.7 on 2021-06-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('topic', models.CharField(max_length=130)),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='duration of quiz in minutes')),
                ('required_score_to_pass', models.IntegerField(help_text='requied score in percentage')),
                ('difficulty', models.CharField(choices=[('hard', 'hard'), ('easy', 'easy'), ('medium', 'medium')], max_length=6)),
            ],
        ),
    ]
